name = "Tensura Server"
author = "Notatum"
version = "1.21.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "26b99a4e53fe8c7e20b106ac0e5710671ee58bd8d4cbcebeb9a577bc5d065b54"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
