name = "Tensura Server"
author = "Notatum"
version = "1.21.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e177f32fb0f26f9daad2fdd30e00ba0197b97408d06481fec7e64680631cc28c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
