name = "Tensura Server"
author = "Notatum"
version = "1.21.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "081ad0831239022ebdf09fe54d08c7ae281c7fb22f5aaa846c04fa0daaaea08c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
