#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Sep 03 12:39:49 GMT-03:00 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=ComplementaryUnbound_r5.9 + EuphoriaPatches_1.10.0
