# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"
# The chunk rebuild scheduler mode (immediate, culling).
chunk_rebuild_scheduler = "culling"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enables dynamic lighting of beacon or end gateway beams.
	beam = true
	# Enables dynamic lighting of firefly particles from Firefly Bushes.
	firefly = true
	# Enables dynamic lighting for entities that have the Glowing effect.
	glowing_effect = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Enables dynamic lighting of the Warden's sonic boom attack particles.
	sonic_boom = true
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"
	# Enables dynamic lighting of Guardian's lasers. This also can be toggled off by disabling Guardian dynamic lighting.
	guardian_laser = true

			[light_sources.settings.entities.minecraft]
				pale_oak_boat = true
				zombie_horse = true
				axolotl = true
				egg = true
				zoglin = true
				spawner_minecart = true
				allay = true
				jungle_chest_boat = true
				llama = true
				mule = true
				bat = true
				husk = true
				experience_bottle = true
				camel = true
				rabbit = true
				firework_rocket = true
				silverfish = true
				happy_ghast = true
				giant = true
				drowned = true
				creaking = true
				item = true
				oak_chest_boat = true
				goat = true
				horse = true
				vindicator = true
				birch_boat = true
				minecart = true
				spectral_arrow = true
				oak_boat = true
				llama_spit = true
				mooshroom = true
				glow_item_frame = false
				snowball = true
				tnt = true
				parrot = true
				creeper = true
				lightning_bolt = true
				tadpole = true
				ravager = true
				evoker_fangs = true
				chest_minecart = true
				tropical_fish = true
				slime = true
				pillager = true
				parched = true
				dark_oak_chest_boat = true
				area_effect_cloud = true
				blaze = true
				piglin = true
				end_crystal = true
				endermite = true
				zombie = true
				ender_pearl = true
				item_display = true
				breeze_wind_charge = true
				guardian = true
				fireball = true
				illusioner = true
				eye_of_ender = true
				wither_skull = true
				wolf = true
				zombie_nautilus = true
				zombie_villager = true
				tnt_minecart = true
				block_display = true
				elder_guardian = true
				cherry_chest_boat = true
				acacia_chest_boat = true
				small_fireball = true
				strider = true
				cave_spider = true
				witch = true
				cod = true
				snow_golem = true
				spider = true
				command_block_minecart = true
				panda = true
				bee = true
				arrow = true
				mannequin = true
				lingering_potion = true
				cow = true
				birch_chest_boat = true
				magma_cube = true
				pig = true
				skeleton = true
				spruce_boat = true
				frog = true
				hoglin = true
				armadillo = true
				splash_potion = true
				armor_stand = true
				experience_orb = true
				dolphin = true
				stray = true
				jungle_boat = true
				shulker = true
				turtle = true
				salmon = true
				wandering_trader = true
				wither_skeleton = true
				vex = true
				piglin_brute = true
				breeze = true
				nautilus = true
				ocelot = true
				acacia_boat = true
				pale_oak_chest_boat = true
				furnace_minecart = true
				mangrove_boat = true
				item_frame = true
				phantom = true
				ender_dragon = true
				sulfur_cube = true
				leash_knot = true
				evoker = true
				marker = true
				glow_squid = true
				warden = true
				squid = true
				shulker_bullet = true
				enderman = true
				dragon_fireball = true
				copper_golem = true
				chicken = true
				sniffer = true
				dark_oak_boat = true
				trader_llama = true
				donkey = true
				bamboo_chest_raft = true
				bogged = true
				bamboo_raft = true
				fox = true
				mangrove_chest_boat = true
				camel_husk = true
				cherry_boat = true
				iron_golem = true
				zombified_piglin = true
				cat = true
				wind_charge = true
				ghast = true
				sheep = true
				player = true
				pufferfish = true
				trident = true
				villager = true
				skeleton_horse = true
				ominous_item_spawner = true
				fishing_bobber = true
				text_display = true
				polar_bear = true
				hopper_minecart = true
				falling_block = true
				painting = true
				interaction = true
				wither = true
				spruce_chest_boat = true
				boat = true
				chest_boat = true
				potion = true

			[light_sources.settings.entities.tensura]
				direwolf = true
				hound_dog = true
				slime = true
				metal_slime = true
				barghest = true
				dragon_peacock = true
				leech_lizard = true
				cattledeer = true
				spear_toro = true
				holy_water = true
				akash = true
				flame_breath = true
				black_flame_breath = true
				thunder_breath = true
				ice_breath = true
				paralysing_breath = true
				fishing_hook = true
				knight_spider = true
				black_spider = true
				armorsaurus = true
				army_wasp = true
				giant_cod = true
				bullet = true
				aura_bullet = true
				invisible_fire_bolt = true
				web_bullet = true
				tensura_boat = true
				tensura_chest_boat = true
				ranged_barrier = true
				boss_barrier = true
				basilisk = true
				death_blessing = true
				falling_block = true
				water_ball = true
				frost_ball = true
				fire_ball = true
				black_flame_ball = true
				plasmas_ball = true
				steam_ball = true
				poison_ball = true
				acid_ball = true
				megiddo_bubble = true
				one_eyed_owl = true
				falmuth_knight = true
				holy_field = true
				gravity_field = true
				charybdis = true
				darkness_cannon = true
				evil_centipede = true
				evil_centipede_body = true
				clone = true
				elemental_colossus = true
				horned_rabbit = true
				poison_cutter = true
				severance_cutter = true
				dimension_cut_projectile = true
				space_cut_projectile = true
				dark_cube = true
				unicorn_horn = true
				explosion_circle = true
				flare_circle = true
				magic_circle = true
				lesser_daemon = true
				arch_daemon = true
				disintegration = true
				chaos_eater = true
				magma_shot = true
				reflector_echo = true
				electro_blast = true
				dwarf = true
				tempest_scale = true
				aura_shield = true
				magic_shield = true
				monster_spit = true
				heat_sphere = true
				gravity_sphere = true
				flame_sphere = true
				thunder_sphere = true
				wind_sphere = true
				lightning_sphere = true
				float_sphere = true
				severer_blade_projectile = true
				skeleton = true
				magic_explosion = true
				phantaspore = true
				speared_fin_arrow = true
				light_arrow = true
				spatial_arrow = true
				invisible_arrow = true
				hazy_blossom = true
				folgen = true
				hellfire = true
				winged_cat = true
				gazel_dwargo = true
				beast_gnome = true
				war_gnome = true
				goblin = true
				water_breath = true
				greater_daemon = true
				sniper_grenade = true
				solar_grenade = true
				bone_golem = true
				haki_field = true
				sacred_haki_field = true
				solar_beam = true
				marionette_lines = true
				hinata_sakaguchi = true
				giant_ant = true
				ifrit = true
				ifrit_clone = true
				kirara_mizutani = true
				kunai = true
				kyoya_tachibana = true
				hover_lizard = true
				spear = true
				fire_lance = true
				ice_lance = true
				thunder_lance = true
				lightning_lance = true
				hell_flare_limited = true
				healing_rain = true
				thunder_rain = true
				acid_rain = true
				mai_furuki = true
				curse_bind_hands = true
				shadow_bind_hands = true
				mud_hands = true
				mark_lauren = true
				megalodon = true
				fusionist_landmine = true
				giant_bat = true
				training_dummy = true
				gourmet_mist = true
				gluttony_mist = true
				blood_mist = true
				sleep_mist = true
				predator_mist = true
				miasmic_mist = true
				charybdis_core = true
				thrown_item = true
				flame_orb = true
				mad_orbs = true
				orc = true
				hell_caterpillar = true
				horned_bear = true
				giant_bear = true
				wind_blade = true
				pegacorn = true
				pegasus = true
				landfish = true
				fusionist_projectile = true
				fire_pillar = true
				ice_pillar = true
				earth_pillar = true
				healing_potion = true
				hell_moth = true
				warp_portal = true
				water_jail = true
				air_jail = true
				fire_jail = true
				mud_spike = true
				icicle_spike = true
				aqua_frog = true
				black_lightning_blast = true
				fire_bolt = true
				summoning_beam = true
				blood_ray = true
				spatial_ray = true
				black_lightning_bolt = true
				salamander = true
				giant_salmon = true
				feathered_serpent = true
				orc_lord = true
				shin_ryusei = true
				shinji_tanimura = true
				shizu = true
				shogo_taguchi = true
				sissie = true
				supermassive_slime = true
				wind_breath = true
				sylphide = true
				aura_slash = true
				tempest_serpent = true
				tempest_serpent_body = true
				blade_tiger = true
				mud_shot = true
				obsidian_shot = true
				stone_shot = true
				bog_shot = true
				heat_storm = true
				fire_storm = true
				earth_storm = true
				wind_tornado = true
				death_tornado = true
				undine = true
				unicorn = true
				blizzard = true
				zombie = true
				poisonous_breath = true
				water_blade = true
				lizardman = true
				hell_flare = true
				orc_disaster = true
				hell_flare_projectile = true
				boulder_shot = true
				earth_spike = true
				lightning_bolt = true
				anti_shock_area = true
				anti_magic_area = true

[debug]
	active_dynamic_lighting_cells = false
	display_dynamic_lighting_chunk_rebuild = false
	display_behavior_bounding_box = false

[adaptive_ticking]
	# Reduces how often sources behind the camera get ticked.
	background_sleep = true
	# How far away (in chunks) until light sources get ticked less often.
	slow = 5
	# How far away (in chunks) until light sources get ticked even less often.
	slower = 8
